### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'allowed' and 'gots'

### ISSUE THREAD

**Issue by pawamoy** [youngquan/pip-download#25]
I got this traceback a few seconds ago:

```console
pip-download torchvision==0.6.1
Using `python-versions` in config file.
Using `platform-tags` in config file.
We are using pip download command to download package torchvision==0.6.1
--------------------------------------------------
Looking in indexes: https://pypi.org/simple/
Collecting torchvision==0.6.1
  Using cached https://pypi.org/packages/packages/9a/f1/535a407b4a265adf2dd7c2c2458217e37c5fe83ec97234e66c564592a9a0/torchvision-0.6.1-cp36-cp36m-manylinux1_x86_64.whl (6.6 MB)
Collecting numpy
  Using cached https://pypi.org/packages/packages/14/32/d3fa649ad7ec0b82737b92fefd3c4dd376b0bb23730715124569f38f3a08/numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Collecting torch==1.5.1
  Using cached https://pypi.org/packages/packages/62/01/457b49d790b6c4b9720e6f9dbbb617692f6ce8afdaadf425c055c41a7416/torch-1.5.1-cp36-cp36m-manylinux1_x86_64.whl (753.2 MB)
Collecting pillow>=4.1.1
  Using cached https://pypi.org/packages/packages/c9/9a/b24a14a409a65dc467213f6a3518809eb56e9782c07d7269900216a6439d/Pillow-8.1.1-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
Collecting future
  Using cached https://pypi.org/packages/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829 kB)
Saved /tmp/pipdownload-6f12dtvc/torchvision-0.6.1-cp36-cp36m-manylinux1_x86_64.whl
Saved /tmp/pipdownload-6f12dtvc/torch-1.5.1-cp36-cp36m-manylinux1_x86_64.whl
Saved /tmp/pipdownload-6f12dtvc/Pillow-8.1.1-cp36-cp36m-manylinux1_x86_64.whl
Saved /tmp/pipdownload-6f12dtvc/future-0.18.2.tar.gz
Saved /tmp/pipdownload-6f12dtvc/numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl
Successfully downloaded torchvision torch pillow future numpy
The file /home/user/official/numpy-1.19.5-cp38-cp38-manylinux2010_i686.whl has already been downloaded.
Downloading file numpy-1.19.5-cp39-cp39-manylinux2010_x86_64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp37-cp37m-win_amd64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
The file /home/user/official/numpy-1.19.5-cp37-cp37m-manylinux1_i686.whl has already been downloaded.
The file /home/user/official/numpy-1.19.5-cp38-cp38-manylinux1_i686.whl has already been downloaded.
Downloading file numpy-1.19.5.zip: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp36-cp36m-manylinux2010_i686.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp38-cp38-manylinux2014_aarch64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp38-cp38-manylinux1_x86_64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp39-cp39-manylinux1_i686.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp37-cp37m-manylinux2010_i686.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
The file /home/user/official/numpy-1.19.5-cp39-cp39-manylinux1_x86_64.whl has already been downloaded.
The file /home/user/official/numpy-1.19.5-cp39-cp39-manylinux2014_aarch64.whl has already been downloaded.
Downloading file numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp37-cp37m-manylinux1_x86_64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Downloading file numpy-1.19.5-cp38-cp38-win_amd64.whl: 
[Processing]:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>100.00%
Traceback (most recent call last):
  File "/home/user/.local/bin/pip-download", line 8, in <module>
    sys.exit(pipdownload())
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/pipdownload/cli.py", line 260, in pipdownload
    download(file, dest_dir)
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/pipdownload/utils.py", line 260, in download
    hashes.check_against_path(download_file_path)
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/pipdownload/utils.py", line 173, in check_against_path
    return self.check_against_file(file)
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/pipdownload/utils.py", line 169, in check_against_file
    return self.check_against_chunks(read_chunks(file))
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/pipdownload/utils.py", line 158, in check_against_chunks
    self._raise(gots)
  File "/home/user/.local/pipx/venvs/pip-download/lib64/python3.6/site-packages/pipdownload/utils.py", line 161, in _raise
    raise HashMismatch
TypeError: __init__() missing 2 required positional arguments: 'allowed' and 'gots'
```

Any idea on what's happening 😄 ?

**Comment by pawamoy** [comment]
A quick fix would be to write `raise HashMismatch({}, got)` at https://github.com/youngquan/pip-download/blob/master/pipdownload/utils.py#L161. Not sure what the `allowed` argument should look like, even after reading its description in the class 🙂

**Comment by pawamoy** [comment]
OK I see what happened. I interrupted the previous run, which left a file in bad state:

> Previously-downloaded file numpy-1.19.5-cp37-cp37m-manylinux2014_aarch64.whl has bad hash. Re-downloading.

This is where the exception was triggered. The fix mentioned above worked, and I was able to resume the download.
