### ISSUE TITLE
pip-download requires tzlocal==2.1

### ISSUE THREAD

**Issue by zacharyforbush** [youngquan/pip-download#28]
When trying to run pip-download to pull down a package on a fresh python:latest container, the application crashes complaining about not knowing the timezone.

Working around the issue is possible simply by installing tzlocal==2.1 (i.e., 'pip install tzlocal==2.1'). 

Perhaps this dependency should be included when installing pip-download?

```
[user@host~]$ docker run -it python /bin/bash
root@host:/# pip install pip-download
Collecting pip-download
  Downloading pip_download-0.4.1-py3-none-any.whl (14 kB)

[...]

Installing collected packages: urllib3, idna, charset-normalizer, certifi, six, requests, pyparsing, msgpack, tzlocal, retrying, pip-api, packaging, click, cachecontrol, appdirs, pip-download
Successfully installed appdirs-1.4.4 cachecontrol-0.12.6 certifi-2021.5.30 charset-normalizer-2.0.4 click-8.0.1 idna-3.2 msgpack-1.0.2 packaging-21.0 pip-api-0.0.20 pip-download-0.4.1 pyparsing-2.4.7 requests-2.26.0 retrying-1.3.3 six-1.16.0 tzlocal-3.0 urllib3-1.26.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@4448dae2f0f6:/# pip-download pylint
Traceback (most recent call last):
  File "/usr/local/bin/pip-download", line 8, in <module>
    sys.exit(pipdownload())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipdownload/cli.py", line 158, in pipdownload
    if tz.zone in ["Asia/Shanghai", "Asia/Chongqing"]:
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'zone'
```

```
root@host:/# pip install tzlocal==2.1
Collecting tzlocal==2.1
  Downloading tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Collecting pytz
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 4.2 MB/s
Installing collected packages: pytz, tzlocal
  Attempting uninstall: tzlocal
    Found existing installation: tzlocal 3.0
    Uninstalling tzlocal-3.0:
      Successfully uninstalled tzlocal-3.0
Successfully installed pytz-2021.1 tzlocal-2.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@host:/# pip-download pylint
We are using pip download command to download package pylint
--------------------------------------------------
Collecting pylint
  Downloading pylint-2.10.2-py3-none-any.whl (392 kB)
     |████████████████████████████████| 392 kB 4.1 MB/s

[...]

All packages have been downloaded successfully!
```

**Comment by zacharyforbush** [comment]
Thanks for the fix!
